import { collectionLabels } from '../config/appConfig';

const featureMap = {
  clubProfile: {
    key: 'clubProfile',
    title: collectionLabels.clubProfile,
    icon: 'business-outline',
    collectionName: 'clubProfiles',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: false,
    allowRoles: ['admin'],
    listFields: ['name', 'description', 'updatedAt'],
    fields: [
      { key: 'name', label: 'Kulup Adi', type: 'text', required: true },
      { key: 'description', label: 'Aciklama', type: 'textarea' },
      { key: 'logo', label: 'Logo URL', type: 'text' },
    ],
  },
  secretaries: {
    key: 'secretaries',
    title: collectionLabels.secretaries,
    icon: 'people-outline',
    collectionName: 'users',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin'],
    listFields: ['name', 'email', 'createdAt'],
    formMode: 'managedUser',
    managedRole: 'secretary',
    fields: [
      { key: 'name', label: 'Ad Soyad', type: 'text', required: true },
      { key: 'email', label: 'E-posta', type: 'text', required: true },
      { key: 'password', label: 'Sifre', type: 'text', required: true, createOnly: true },
    ],
  },
  branches: {
    key: 'branches',
    title: collectionLabels.branches,
    icon: 'git-branch-outline',
    collectionName: 'branches',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin'],
    listFields: ['name', 'address', 'phone'],
    fields: [
      { key: 'name', label: 'Sube Adi', type: 'text', required: true },
      { key: 'address', label: 'Adres', type: 'textarea' },
      { key: 'phone', label: 'Telefon', type: 'text' },
    ],
  },
  trainers: {
    key: 'trainers',
    title: collectionLabels.trainers,
    icon: 'body-outline',
    collectionName: 'trainers',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin'],
    listFields: ['name', 'email', 'branchesLabel'],
    formMode: 'managedUser',
    managedRole: 'trainer',
    fields: [
      { key: 'name', label: 'Ad Soyad', type: 'text', required: true },
      { key: 'email', label: 'E-posta', type: 'text', required: true },
      { key: 'password', label: 'Sifre', type: 'text', required: true, createOnly: true },
      { key: 'branches', label: 'Subeler', type: 'multiselect', optionsSource: 'branches' },
    ],
  },
  schedules: {
    key: 'schedules',
    title: collectionLabels.schedules,
    icon: 'time-outline',
    collectionName: 'schedules',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin', 'trainer'],
    listFields: ['day', 'time', 'capacity', 'branchLabel'],
    fields: [
      { key: 'branchId', label: 'Sube', type: 'select', optionsSource: 'branches', required: true },
      { key: 'trainerId', label: 'Antrenor', type: 'select', optionsSource: 'trainers', required: true },
      { key: 'day', label: 'Gun', type: 'select', required: true, options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] },
      { key: 'time', label: 'Saat', type: 'text', required: true },
      { key: 'capacity', label: 'Kapasite', type: 'number', required: true },
      { key: 'lessonsCount', label: 'Ders Sayisi', type: 'number' },
    ],
  },
  prices: {
    key: 'prices',
    title: collectionLabels.prices,
    icon: 'cash-outline',
    collectionName: 'prices',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin'],
    listFields: ['price', 'branchLabel', 'scheduleLabel'],
    fields: [
      { key: 'branchId', label: 'Sube', type: 'select', optionsSource: 'branches', required: true },
      { key: 'scheduleId', label: 'Ders Saati', type: 'select', optionsSource: 'schedules', required: true },
      { key: 'price', label: 'Fiyat', type: 'number', required: true },
    ],
  },
  events: {
    key: 'events',
    title: collectionLabels.events,
    icon: 'calendar-outline',
    collectionName: 'events',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin', 'parent'],
    listFields: ['title', 'date', 'location'],
    fields: [
      { key: 'title', label: 'Baslik', type: 'text', required: true },
      { key: 'description', label: 'Aciklama', type: 'textarea' },
      { key: 'date', label: 'Tarih', type: 'date', required: true },
      { key: 'location', label: 'Konum', type: 'text' },
    ],
  },
  announcements: {
    key: 'announcements',
    title: collectionLabels.announcements,
    icon: 'megaphone-outline',
    collectionName: 'announcements',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin', 'parent'],
    listFields: ['title', 'target', 'createdAt'],
    fields: [
      { key: 'title', label: 'Baslik', type: 'text', required: true },
      { key: 'content', label: 'Icerik', type: 'textarea', required: true },
      { key: 'target', label: 'Hedef', type: 'select', required: true, options: ['all', 'trainers', 'schedule'] },
      { key: 'branchId', label: 'Sube', type: 'select', optionsSource: 'branches' },
      { key: 'scheduleId', label: 'Ders Saati', type: 'select', optionsSource: 'schedules' },
    ],
  },
  products: {
    key: 'products',
    title: collectionLabels.products,
    icon: 'cart-outline',
    collectionName: 'products',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['superadmin', 'admin', 'trainer', 'parent'],
    listFields: ['name', 'price', 'stock'],
    fields: [
      { key: 'name', label: 'Urun Adi', type: 'text', required: true },
      { key: 'description', label: 'Aciklama', type: 'textarea' },
      { key: 'price', label: 'Fiyat', type: 'number', required: true },
      { key: 'stock', label: 'Stok', type: 'number' },
      { key: 'imageUrl', label: 'Gorsel URL', type: 'text' },
    ],
  },
  standards: {
    key: 'standards',
    title: collectionLabels.standards,
    icon: 'trophy-outline',
    collectionName: 'standards',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['superadmin', 'admin', 'trainer', 'parent'],
    listFields: ['name', 'style', 'distance', 'targetTime'],
    fields: [
      { key: 'name', label: 'Standart Adi', type: 'text', required: true },
      { key: 'style', label: 'Stil', type: 'text', required: true },
      { key: 'distance', label: 'Mesafe', type: 'number', required: true },
      { key: 'targetTime', label: 'Hedef Sure', type: 'text' },
      { key: 'birthYear', label: 'Dogum Yili', type: 'number' },
      { key: 'gender', label: 'Cinsiyet', type: 'select', options: ['female', 'male', 'mixed'] },
    ],
  },
  discounts: {
    key: 'discounts',
    title: collectionLabels.discounts,
    icon: 'pricetag-outline',
    collectionName: 'discounts',
    supportsCreate: true,
    supportsEdit: false,
    supportsDelete: true,
    allowRoles: ['admin'],
    listFields: ['code', 'discountPercent', 'expiryDate'],
    fields: [
      { key: 'code', label: 'Kod', type: 'text', required: true },
      { key: 'discountPercent', label: 'Indirim Yuzdesi', type: 'number' },
      { key: 'discountAmount', label: 'Sabit Indirim', type: 'number' },
      { key: 'expiryDate', label: 'Son Gecerlilik', type: 'date' },
      { key: 'maxUsage', label: 'Maksimum Kullanim', type: 'number' },
    ],
  },
  students: {
    key: 'students',
    title: collectionLabels.students,
    icon: 'school-outline',
    collectionName: 'students',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['admin', 'secretary', 'trainer'],
    listFields: ['fullName', 'parentName', 'status', 'branchLabel'],
    formMode: 'student',
    fields: [
      { key: 'name', label: 'Ad', type: 'text', required: true },
      { key: 'surname', label: 'Soyad', type: 'text', required: true },
      { key: 'age', label: 'Yas', type: 'number' },
      { key: 'phone', label: 'Telefon', type: 'text' },
      { key: 'parentName', label: 'Veli Adi', type: 'text', required: true },
      { key: 'parentEmail', label: 'Veli E-posta', type: 'text', required: true },
      { key: 'parentPhone', label: 'Veli Telefon', type: 'text' },
      { key: 'parentPassword', label: 'Veli Sifresi', type: 'text', createOnly: true },
      { key: 'address', label: 'Adres', type: 'textarea' },
      { key: 'branchId', label: 'Sube', type: 'select', optionsSource: 'branches', required: true },
      { key: 'scheduleId', label: 'Ders Saati', type: 'select', optionsSource: 'schedules', required: true },
      { key: 'monthlyPrice', label: 'Aylik Ucret', type: 'number' },
      { key: 'installmentCount', label: 'Taksit Sayisi', type: 'number' },
      { key: 'totalAmount', label: 'Toplam Tutar', type: 'number' },
      { key: 'status', label: 'Durum', type: 'select', options: ['active', 'inactive'] },
    ],
  },
  payments: {
    key: 'payments',
    title: collectionLabels.payments,
    icon: 'wallet-outline',
    collectionName: 'payments',
    supportsCreate: true,
    supportsEdit: false,
    supportsDelete: false,
    allowRoles: ['admin', 'secretary', 'parent'],
    listFields: ['studentLabel', 'amount', 'status', 'paidAt'],
    formMode: 'payment',
    fields: [
      { key: 'studentId', label: 'Ogrenci', type: 'select', optionsSource: 'students', required: true },
      { key: 'amount', label: 'Tutar', type: 'number', required: true },
      { key: 'status', label: 'Durum', type: 'select', required: true, options: ['pending', 'paid'] },
      { key: 'method', label: 'Yontem', type: 'select', options: ['cash', 'eft', 'card'] },
      { key: 'dueDate', label: 'Vade', type: 'date' },
      { key: 'paidAt', label: 'Odeme Tarihi', type: 'date' },
      { key: 'note', label: 'Not', type: 'textarea' },
    ],
  },
  incomes: {
    key: 'incomes',
    title: collectionLabels.incomes,
    icon: 'trending-up-outline',
    collectionName: 'incomes',
    supportsCreate: true,
    supportsEdit: false,
    supportsDelete: true,
    allowRoles: ['admin'],
    listFields: ['description', 'amount', 'date'],
    fields: [
      { key: 'description', label: 'Aciklama', type: 'text', required: true },
      { key: 'amount', label: 'Tutar', type: 'number', required: true },
      { key: 'date', label: 'Tarih', type: 'date', required: true },
    ],
  },
  expenses: {
    key: 'expenses',
    title: collectionLabels.expenses,
    icon: 'trending-down-outline',
    collectionName: 'expenses',
    supportsCreate: true,
    supportsEdit: false,
    supportsDelete: true,
    allowRoles: ['admin'],
    listFields: ['description', 'amount', 'date'],
    fields: [
      { key: 'description', label: 'Aciklama', type: 'text', required: true },
      { key: 'amount', label: 'Tutar', type: 'number', required: true },
      { key: 'category', label: 'Kategori', type: 'text' },
      { key: 'date', label: 'Tarih', type: 'date', required: true },
    ],
  },
  attendance: {
    key: 'attendance',
    title: collectionLabels.attendance,
    icon: 'checkbox-outline',
    collectionName: 'attendance',
    supportsCreate: true,
    supportsEdit: false,
    supportsDelete: false,
    allowRoles: ['trainer', 'parent'],
    listFields: ['studentLabel', 'date', 'status'],
    fields: [
      { key: 'studentId', label: 'Ogrenci', type: 'select', optionsSource: 'students', required: true },
      { key: 'scheduleId', label: 'Ders Saati', type: 'select', optionsSource: 'schedules' },
      { key: 'date', label: 'Tarih', type: 'date', required: true },
      { key: 'status', label: 'Durum', type: 'select', required: true, options: ['attended', 'missed', 'late'] },
      { key: 'note', label: 'Not', type: 'textarea' },
    ],
  },
  performances: {
    key: 'performances',
    title: collectionLabels.performances,
    icon: 'analytics-outline',
    collectionName: 'performances',
    supportsCreate: true,
    supportsEdit: false,
    supportsDelete: false,
    allowRoles: ['trainer', 'parent', 'superadmin'],
    listFields: ['studentLabel', 'style', 'timing', 'eventDate'],
    fields: [
      { key: 'studentId', label: 'Ogrenci', type: 'select', optionsSource: 'students', required: true },
      { key: 'style', label: 'Stil', type: 'text', required: true },
      { key: 'distance', label: 'Mesafe', type: 'number', required: true },
      { key: 'timing', label: 'Sure', type: 'text', required: true },
      { key: 'grade', label: 'Puan', type: 'number' },
      { key: 'eventDate', label: 'Tarih', type: 'date', required: true },
      { key: 'source', label: 'Kaynak', type: 'text' },
    ],
  },
  workouts: {
    key: 'workouts',
    title: collectionLabels.workouts,
    icon: 'fitness-outline',
    collectionName: 'workouts',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['trainer', 'parent'],
    listFields: ['name', 'published', 'createdAt'],
    fields: [
      { key: 'name', label: 'Antrenman Adi', type: 'text', required: true },
      { key: 'scheduleId', label: 'Ders Saati', type: 'select', optionsSource: 'schedules' },
      { key: 'exercisesText', label: 'Egzersizler JSON', type: 'textarea' },
      { key: 'published', label: 'Yayinlandi', type: 'boolean' },
    ],
  },
  admins: {
    key: 'admins',
    title: collectionLabels.admins,
    icon: 'shield-checkmark-outline',
    collectionName: 'users',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['superadmin'],
    formMode: 'managedUser',
    managedRole: 'admin',
    listFields: ['name', 'email', 'membershipEnd'],
    fields: [
      { key: 'name', label: 'Ad Soyad', type: 'text', required: true },
      { key: 'email', label: 'E-posta', type: 'text', required: true },
      { key: 'password', label: 'Sifre', type: 'text', required: true, createOnly: true },
      { key: 'membershipStart', label: 'Uyelik Baslangic', type: 'date', required: true },
      { key: 'membershipEnd', label: 'Uyelik Bitis', type: 'date', required: true },
      { key: 'membershipPrice', label: 'Uyelik Tutari', type: 'number' },
      { key: 'membershipInstallments', label: 'Taksit Sayisi', type: 'number' },
    ],
  },
  applications: {
    key: 'applications',
    title: collectionLabels.applications,
    icon: 'document-text-outline',
    collectionName: 'applications',
    supportsCreate: false,
    supportsEdit: true,
    supportsDelete: false,
    allowRoles: ['superadmin'],
    listFields: ['name', 'email', 'status', 'createdAt'],
    fields: [
      { key: 'status', label: 'Durum', type: 'select', options: ['pending', 'approved', 'rejected'] },
      { key: 'tempPassword', label: 'Gecici Sifre', type: 'text' },
    ],
  },
  creditPackages: {
    key: 'creditPackages',
    title: collectionLabels.creditPackages,
    icon: 'albums-outline',
    collectionName: 'credit_packages',
    supportsCreate: true,
    supportsEdit: false,
    supportsDelete: true,
    allowRoles: ['superadmin', 'trainer'],
    listFields: ['credit', 'price', 'createdAt'],
    fields: [
      { key: 'credit', label: 'Kredi', type: 'number', required: true },
      { key: 'price', label: 'Fiyat', type: 'number', required: true },
    ],
  },
  creditRequests: {
    key: 'creditRequests',
    title: collectionLabels.creditRequests,
    icon: 'card-outline',
    collectionName: 'credit_requests',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: false,
    allowRoles: ['superadmin', 'trainer'],
    listFields: ['credit', 'amount', 'status', 'createdAt'],
    fields: [
      { key: 'credit', label: 'Talep Edilen Kredi', type: 'number', required: true },
      { key: 'amount', label: 'Odeme Tutari', type: 'number' },
      { key: 'status', label: 'Durum', type: 'select', options: ['pending', 'approved', 'rejected'] },
      { key: 'note', label: 'Not', type: 'textarea' },
    ],
  },
  cashWithdrawalRequests: {
    key: 'cashWithdrawalRequests',
    title: collectionLabels.cashWithdrawalRequests,
    icon: 'cash-outline',
    collectionName: 'cash_withdrawal_requests',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: false,
    allowRoles: ['superadmin', 'trainer'],
    listFields: ['credits', 'status', 'createdAt'],
    fields: [
      { key: 'credits', label: 'Kredi', type: 'number', required: true },
      { key: 'status', label: 'Durum', type: 'select', options: ['pending', 'approved', 'rejected'] },
      { key: 'iban', label: 'IBAN', type: 'text' },
      { key: 'note', label: 'Not', type: 'textarea' },
    ],
  },
  advertisements: {
    key: 'advertisements',
    title: collectionLabels.advertisements,
    icon: 'images-outline',
    collectionName: 'advertisements',
    supportsCreate: true,
    supportsEdit: true,
    supportsDelete: true,
    allowRoles: ['superadmin'],
    listFields: ['title', 'active', 'createdAt'],
    fields: [
      { key: 'title', label: 'Baslik', type: 'text', required: true },
      { key: 'description', label: 'Aciklama', type: 'textarea' },
      { key: 'imageUrl', label: 'Gorsel URL', type: 'text' },
      { key: 'videoUrl', label: 'Video URL', type: 'text' },
      { key: 'active', label: 'Aktif', type: 'boolean' },
    ],
  },
  orders: {
    key: 'orders',
    title: collectionLabels.orders,
    icon: 'receipt-outline',
    collectionName: 'orders',
    supportsCreate: false,
    supportsEdit: true,
    supportsDelete: false,
    allowRoles: ['superadmin', 'trainer', 'parent', 'admin'],
    listFields: ['productName', 'status', 'createdAt'],
    fields: [
      { key: 'status', label: 'Durum', type: 'select', options: ['pending', 'approved', 'prepared', 'shipped', 'completed', 'rejected'] },
      { key: 'trackingCode', label: 'Takip Kodu', type: 'text' },
      { key: 'note', label: 'Not', type: 'textarea' },
    ],
  },
  raceImports: {
    key: 'raceImports',
    title: collectionLabels.raceImports,
    icon: 'speedometer-outline',
    collectionName: 'race_result_imports',
    supportsCreate: false,
    supportsEdit: false,
    supportsDelete: false,
    allowRoles: ['superadmin'],
    listFields: ['fileName', 'matchedCount', 'createdAt'],
    fields: [],
  },
};

export const roleFeatureKeys = {
  superadmin: ['admins', 'applications', 'creditRequests', 'products', 'creditPackages', 'cashWithdrawalRequests', 'standards', 'raceImports', 'advertisements', 'orders'],
  admin: ['clubProfile', 'secretaries', 'branches', 'trainers', 'schedules', 'prices', 'students', 'payments', 'events', 'announcements', 'products', 'standards', 'discounts', 'incomes', 'expenses'],
  secretary: ['students', 'payments'],
  trainer: ['schedules', 'students', 'attendance', 'performances', 'workouts', 'standards', 'products', 'creditPackages', 'creditRequests', 'cashWithdrawalRequests'],
  parent: ['events', 'workouts', 'performances', 'payments', 'attendance', 'standards', 'announcements', 'products', 'orders'],
};

export function getFeatureConfig(featureKey) {
  return featureMap[featureKey];
}

export function getRoleFeatures(role) {
  return (roleFeatureKeys[role] || []).map((key) => featureMap[key]).filter(Boolean);
}

export function canCreateFeature(feature, role) {
  if (!feature?.supportsCreate) return false;
  return (feature.createRoles || feature.allowRoles || []).includes(role);
}

export function canEditFeature(feature, role) {
  if (!feature?.supportsEdit) return false;
  return (feature.editRoles || feature.allowRoles || []).includes(role);
}

export function canDeleteFeature(feature, role) {
  if (!feature?.supportsDelete) return false;
  return (feature.deleteRoles || feature.allowRoles || []).includes(role);
}