// Mobil uygulama tasarim sistemi web premium-system.css ile birebir hizalanmistir.

export const palette = {
  primary: '#0b7ea8',
  primaryDark: '#085a78',
  primaryLight: '#e8f6fc',
  accent: '#14b8a6',
  accentDeep: '#0d9488',
  bg: '#f0f4f8',
  surface: '#ffffff',
  surfaceAlt: '#f8fafc',
  text: '#1e293b',
  textMuted: '#64748b',
  border: '#e2e8f0',
  borderStrong: '#cbd5e1',
  success: '#16a34a',
  successLight: '#dcfce7',
  warning: '#d97706',
  warningLight: '#fef3c7',
  danger: '#dc2626',
  dangerLight: '#fee2e2',
  info: '#0ea5e9',
  infoLight: '#e0f2fe',
  sidebar: '#0f2942',
  sidebarDeep: '#163a5c',
};

export const theme = {
  colors: {
    background: palette.bg,
    surface: palette.surface,
    surfaceAlt: palette.surfaceAlt,
    primary: palette.primary,
    primaryDeep: palette.primaryDark,
    primaryLight: palette.primaryLight,
    accent: palette.accent,
    accentDeep: palette.accentDeep,
    text: palette.text,
    textMuted: palette.textMuted,
    textInverse: '#ffffff',
    border: palette.border,
    borderStrong: palette.borderStrong,
    success: palette.success,
    successLight: palette.successLight,
    warning: palette.warning,
    warningLight: palette.warningLight,
    danger: palette.danger,
    dangerLight: palette.dangerLight,
    info: palette.info,
    infoLight: palette.infoLight,
    sidebar: palette.sidebar,
    sidebarDeep: palette.sidebarDeep,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 22,
    xl: 28,
  },
  radius: {
    xs: 8,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 22,
    pill: 999,
  },
  touchTarget: 44,
  fontSize: {
    xs: 11,
    sm: 12,
    base: 14,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    display: 28,
  },
  fontWeight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  shadow: {
    sm: {
      shadowColor: '#0f172a',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    card: {
      shadowColor: '#0f172a',
      shadowOpacity: 0.08,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
    floating: {
      shadowColor: '#0f172a',
      shadowOpacity: 0.16,
      shadowRadius: 32,
      shadowOffset: { width: 0, height: 12 },
      elevation: 8,
    },
    primary: {
      shadowColor: palette.primary,
      shadowOpacity: 0.28,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
  },
  gradients: {
    primary: ['#0b7ea8', '#0d9488'],
    sidebar: ['#0f2942', '#163a5c'],
    statCard: ['#ffffff', '#f8fafc'],
    accent: ['#0ea5e9', '#14b8a6'],
  },
};
